version: '3.3'
services:
  dice_game:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dice_game'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dice'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'game'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'game'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - dice-game:/var/lib/mysql
# Names our volume
volumes:
  dice-game: